scanmem/scanmem

gui/GameConqueror.py
gui/backend.py
gui/misc.py

The first commit is the most important one. My own commit aedf069 ("gui: add match offset and region type support") didn't catch all code locations to be modified so that GC is hanging when searching in scan results. Sorry for that!
All other fixes are Python 3 fixes. I've tested them against Python 3.4 and 2.7. I've used the int32 lives value of the HeroAircraft object of the game Chromium B.S.U. to test this. I've frozen the lives to 9 to check if GC does the right thing.

Fix GameConqueror hanging and Python 3 support

---

autogen.sh
debian/control
debian/gameconqueror.install
debian/source/format

Using sbuild to build Debian packages in a chroot environment is quite common. I'm using a Debian Wheezy chroot environment and noticed several issues. This patch set fixes them all.

debian, autogen: fix the Debian package build with sbuild

---

config.h.in
configure.ac
endianness.h

Commit 944a54a0 ("Configurable endianness of data") breaks the build on some systems due to non-standard endianness detection. So replace that with AC_C_BIGENDIAN added to configure.ac and a check if this defines WORDS_BIGENDIAN.
Tested on x86, x86_64 and in a Debian Wheezy ppc QEMU VM by adding "#warning big endian detected" to the "big_endian = true" case.
Fixes: Github issue #88

fix endianness check

---

scanmem.h

The macros strdupa() and strndupa() are GNU specific and not
available on other platforms like e.g. the BSD derivatives this way.
The build fails there. We use the GPL and the macros in the glibc
string.h are under LGPL.
So introduce adapted copies of them and use them if they aren't
defined already. This is legal as the GPL license is compatible
and stricter than the LGPL.
Reported-by: Jonathan Pelletier

scanmem: add strdupa() and strndupa() compatibility macros

---

gui/GameConqueror.py
ptrace.c

Currently, the scan progress update for the user and the front-end are using expensive computations at each and every scanned byte. This is very inefficient as only 10 dots have to be printed and a progress bar has to be updated while processing a memory region or all already found matches.
This patch set reduces the costs of these computations by replacing them with simpler ones and updating the progress less frequently. Both progress updates are combined to improve the performance even more. Already found matches are split into 100 samples at which the progress for the front-end is reported. At every 10th sample a dot is displayed for the user. During initial scan there is a dot displayed for 10% of each memory region. The progress for the front-end is updated in that moment in time as …

Optimize scan progress updates

---

gui/GameConqueror.py
gui/backend.py

Python 3 intentionally doesn't convert from bytes to unicode. This is why the search for string/bytearray freezes in GameConqueror and causes a debug message. So explicitly convert strings returned by scanmem as bytes to unicode.
This has been tested with Python 2.7 and 3.4 and is suitable for 0.15 stable.
Reported-by: calculuswhiz

gui: add support for string/bytearray search with Python 3

---

gui/GameConqueror.py
gui/hexview.py
gui/misc.py

With Python 2 the cursor movement is incorrect. The cursor can't be moved backwards and when moving a line down, then the cursor is also moved one position forward. This makes cursor control unusable. With Python 3 the hexview window even doesn't open at all and a Python debug message is printed instead as the payload data is in bytes and not in unicode. There is a recursion problem on ascii/hex change and conversions of division results to integer are missing.
All this is fixed by this pull request so that this behaves the same with Python 3 as with Python 2 and the hexview becomes actually usable.
The following issues are fixed: #103, #113 and #114.

gui: fix the Hexview (esp. for Python 3)

---

gui/GameConqueror.py
handlers.c
value.c
value.h

When searching for numbers with the differential search (?, <, >, =),
the GUI freezes at the point when it should list the scan results
with Python 2 and 3. Analysis has shown that it happens if "unknown"
or a number as big as the buffer are printed without a type. The
printing to the buffer is completely unchecked. All this has been
touched by commit 1f34f3e7 ("implemented dataarray representation")
the last time back in 2010.
So check if the printing to the buffer results in valid output and
make sure that there is always a type printed. For the error case use
"unknown, [unknown]" to print a type as well. Move the error handling
completely into valtostr() and change the return type to void as it
is the same for all call locations.
If the type is unknown, then the GUI can't and shouldn't …

value/gui: rework error handling in and around valtostr()

---

.gitignore
configure.ac
gui/GameConqueror.py
gui/Makefile.am
gui/backend.py

The Python handling for the GUI is non-standard. This is why the
Python cache isn't generated during the installation. It is
generated when calling gameconqueror instead and causes files to
stay after uninstalling GameConqueror. This is unclean. The
preferred GNU automake way is the following:
http://www.gnu.org/software/automake/manual/html_node/Python.html
Add AM_PATH_PYTHON() to detect the Python interpreter and switch
over to 'python_PYTHON' and 'pythondir' to let automake generate
the Python cache upon installation. But GameConqueror.py needs to
become executable again. Use the 'install-data-hook' and 'chmod'
for that.
Reported-by: @anthraxx
Fixes: GitHub issue #116
Converting strings to utf-8 with the .decode() method has the
problem that not all characters (like e.g. 0xfe) can be …

v0.15.2 Python fixes: Python cache + unicode conversion

---

maps.c

With the 04/2015 Linux kernel commit a87938b2e246
("fs/binfmt_elf.c: fix bug in loading of PIE binaries")
we've noticed that our assumption that nothing gets loaded into
the gap behind the .text region of the executable has proven wrong.
Unrelated regions might be loaded via mmap() to that location.
Scanmem sets the region type to 'misc' instead of 'exe' for the
.rodata, .data and .bss sections of the executable and also the
load address is incorrect this way.
So count the regions belonging to the executable separately and if
there are not at least two of them, don't reset that count and try
to detect further regions belonging to the executable. There must
be at least a .data region. Also remember the load address of the
executable and assign it to the other regions belonging to it.
This …

maps: handle the gap behind .text of the exe

---

.gitignore
Makefile.am
README
autogen.sh
build_for_android.sh
config.h.in
configure.ac
getline.c
getline.h
maps.c
menu.c
readline.c

This is the rework of PR #139.
Changes:
* major rework of the getline() replacement
* wrote an own commit to check for getline() and fgetln() failing configure if both are missing
* reworked or even wrote the commit descriptions
* reduced the number of checks for HAVE_GETLINE by moving the check to getline.h
* reworked the host OS detection with an own commit using the standard method
* fixed a typo in configure.ac changes
* removed the ndk-build method completely as it is not ready for the mainline yet
* removed setting of the "-pie" and "-fPIE" flags (can be done by exporting CFLAGS and LDFLAGS)
@funmungus, please review and test. This is what I would want to merge.
You've put too much stuff into your PR and haven't documented your commits correctly. This causes big delays as …

Add Android standalone toolchain build support

---

gui/GameConqueror.py

First new feature for v0.17.
Uses lower level Gtk API to fill the Liststore much faster, allowing to x10 the results displayed.
The second commit takes advantage of the manual conversion needed for the 1st to check the manually added addresses as uints.
Finally closes #196 .

Gui: Improve filling speed of Scanresult liststore

---

gui/GameConqueror.py
gui/GameConqueror.xml
gui/backend.py
ptrace.c
scanmem.c
scanmem.h

Adds a global variable, editable by the front-end and periodically read by the back-end during scan, to stop the current scan and retain only the values obtained till then.
Also adds the gui button to actually use the feature.
Obvious use case: scanning `firefox` takes a couple of minutes, if I got the value wrong I want to terminate the scan ASAP.
The checking is very coarse on purpose, to have minimal impact on the scan.
This is an important feature for me, planned for v0.17, as it changes the API.
@sriemer and @bkazemi , see any problem?

Add a stop scan mechanism

---

handlers.c
ptrace.c
scanroutines.c
scanroutines.h
value.c
value.h

I'm pulling in a rework of the variable length types (VLT for short) scan functions, salient points:
* Implement basic incoming memory length-checking, which offers a bit more safety and fixes the VLT returning from deletion of #204 .
* Massively optimize both small lengths (time -60%) and immediately not matching big lengths (-50%)'s scan time
* Rework bytearray wildcards, for another 15% speedup stacked on
* Finally closes #226 , as now VLT length is fully exploited
This PR features a fair share of type punning via pointer casting, I'm 99.9% sure that I've not introduced unaligned access on ARM, because the pointers I recast and dereference have enough alignment anyway, but I'd appreciate if someone could check on ARM.

Variable length types scan speedup

---

Makefile.am
commands.c
common.h
gui/GameConqueror.py
gui/backend.py
handlers.c
main.c
menu.c
menu.h
scanmem.c
scanmem.h

Set of changes that should completely separate libscanmem from the CLI frontend, finally closing #186 .
This superseded #262 , which I closed earlier.
Highlights:
* Removed everything that's not a main `sm_*` function from `scanmem.h`
* Made both `menu.{h,c}` and `readline.{h,c}` sm dependences instead of libsm dependencies. libsm compiles without both. Complete independence of libsm from libreadline requires a bit more autotools meddling
* Expose only `sm_*` and `show_*` in the dynamic library, which seems a reasonable interface to maintain, instead of exposing basically everything
* Bring proper end-of-life cleanup to front-ends (the GUI used to hope that the OS would reclaim sm's memory at closure, now it actually calls `free()`)
The API still isn't final (that's why I didn't update …

Full libscanmem separation

---

handlers.c

Previously, we'd check if the `matches` struct is NULL, which may
be initialized when we have no matches.

handlers: check for matches properly

---

endianness.h
handlers.c
ptrace.c
scanmem.h
scanroutines.c
scanroutines.h
targetmem.c
targetmem.h
value.c
value.h

This PR completely rehauls the interface with which the process memory is processed by `searchregions()` and the scan functions.
The main commit of the bunch is 0e44526 , which has the rationale, a through list of changes and the advantages we obtain.
Some discussion points:
* A packed struct (`mem64_t`) is introduced to operate on 8-bytes chunks regardless of alignment, instead of copying them out each time. This *should* work (and passes a full `-fsanitize=address,undefined` run on amd64), but needs through testing on ARM (and maybe on i386).
* To provide a common `searchregion()` interface I had `ptrace()` fill the `data` buffer even in the `!HAVE_PROCMEM` case. If the extra consumed memory in this case is unacceptable, I'm open to alternative solutions, like refilling a smaller buffer …

Incoming memory rewrite

---

handlers.c
handlers.h
list.c
list.h
targetmem.c
targetmem.h

Use the new set type to add ranges support to `dregion`, and update its documentation.
Also change `delete_by_region()` in `delete_in_address_range()`, which can be used for the same purpose (and maybe even exposed to users in a future handler), and allows targetmem to "not know" about maps.
I'd like this to go in before #275 , so I can add the extra include cleanup in the second commit of #275 .

Add ranges support to `dregion`

---

commands.c
endianness.h
handlers.c
interrupt.h
list.c
maps.c
maps.h
ptrace.c
scanmem.h
scanroutines.c
show_message.c
targetmem.c
targetmem.h
value.c
value.h

I'm pulling in a series of reworks that dramatically speed up storing data in the matches array, for a total of roughly 55% (measure as snapshot time, for which this was the bottleneck).
* First commit is mostly cosmetic, but I'd like someone to check when I touch the `set` handler
* Second should fully rationalize includes, I'd like to be sure it compiles on other distros as well, speed neutral
* 3rd and 5th are improvements to `add_element()`
* 4th is the main part, a full rework of the `match_flags` type, same interface but much saner (IMHO) implementation, for correctness, portability, speed and no absurd union-derived problems (like having to track the active member, otherwise performance suffers).
Comments welcome.

Targetmem speedup

---

.gitignore
.travis.yml
Makefile.am
configure.ac
main.c
targetmem.h
test/.gitignore
test/Makefile.am
test/memfake.c
test/sm_test.sh

Add a very simple test script and configure the standard autotools facilities to run them.
The tests don't actually check the program output, but are intended to be used with gcc's sanitizers, to catch the sort of bugs that came up in #259 .
Add then the right configuration to `.travis.yml`, so that the tests run themselves automatically at each commit.
Adding for v0.17, comments and further testing ideas welcome.

Add new testing framework

---

AUTHORS
README
gui/gameconqueror.1
main.c
scanmem.1

To finish off tasks for 0.17 ( #278 ) here is the manpage & copyright update.
Manpage is the same posted before.
Add the chat widget to the README, so it's findable.
The change in copyright format is IMHO more reasonable for a collaboration environment like github, or the notice would grow unbounded, but I'm open to suggestions.

Manpage & copyright update

---

Makefile.am
interrupt.c
ptrace.c
scanmem.h

Also:
* Add a new-line during an interrupt for cleaner output.
* s/intused/intr_used/ for clarity.
* New interrupt macro.

cli: allow interrupts mid-scan

---

configure.ac
handlers.c
scanmem.h

Check if `secure_getenv()` is available and define `util_getenv()` depending on that. On Android `secure_getenv()` is not available and `getenv()` is still used there instead.

Introduce util_getenv() based on secure_getenv()

---

configure.ac
handlers.c
ptrace.c
scanmem.h

The middle commit description contains a performance analysis, that I report:
* Memory is read in chunks of 2048 bytes, using larger chunks
does not help dense scans further
* Dense checkmatches time is dramatically decreased, around 3-4x,
as the bottleneck was starting each syscall
* Sparse checkmatches time changed as follows:
* For values not found in the cache, `pread` is ~30% slower than
`ptrace`, this could be mitigated by smaller chucks, but it
cannot be brought below 10% even with chunk size below 8
* Therefore, relative timing depends on "cache occupancy" of
each chunk (2048 bytes),
at 1.3 values per chunk on average they break even
The cases in which this new patch is slower are really absurd, the effect becomes noticeable (> 1 sec) at around 1M values, so you'd need to scan 1M …

Implement procmem support for `checkmatches`

---

ptrace.c

I'm putting this single commit up for review because I'd like to merge this speedup, but I wonder if this isn't actually a slowdown for somebody else with a different compiler.
I'm also not sure when it's worth making the expressions messier for a speedup, but this 10% looks significant enough if you guys see it as well.
----------------------------------
Replace the expressions used for the cache decision with
mathematically equivalent ones (as overflow is impossible in this case),
but that the compiler can optimize better.
On my system (gcc-7, amd64) this saves 10% time in a `snapshot;1` scan.
This optimization is really unstable, as equally simple and functionally
equivalent changes lead to slower code, so those ugly expressions
might be rewritten better once compilers get smarter. …

ptrace: Micro-optimize the comparison expressions in `sm_peekdata()`

---

Makefile.am

As discussed in https://github.com/scanmem/scanmem/pull/302#issuecomment-366688523 , here is the dummy library implementation.
First commit just fixes the `HEADERS`, because new headers were added there by accident.
Second commit adds a library, `libutil.la`, that for now contains only `show_message.c`.
AM builds only the `.a` because of the `noinst` and then links it statically into both sm and libsm.
As a result the `show_*` functions can be dropped from the public API and everything still compiles.
Once this is merged I'll pick up #299 again, move `util_getenv` into its file and add said file to the `libutil_la_SOURCES`.

Add a utilities library

---

Makefile.am
common.h
main.c
menu.c
readline.c
readline.h
scanmem.1
scanmem.h
show_message.c

Add to `main.c` the ability to save and reload the readline history from a config file, in simple cases being `$HOME/.config/scanmem/history`.
I'm not sure this is ready to be merged, it works pretty well and I'd like to hear people's opinions.
Maybe some switches/env to control the file location, or some other behaviour?

scanmem: Add persistence of command history

---

.travis.yml

The gcc option "-fsanitize=address,undefined" requires at least gcc-6
but Travis-CI only provides Ubuntu Trusty environments. The hack to
use a testing toolchain for gcc-6 and binutils 2.26 does not work
any more.
So use docker with the ubuntu:bionic image for the regular build.
It provides gcc-7 as the default gcc.
Reference: #319

.travis.yml: Use docker and Ubuntu Bionic for gcc-7

---

Makefile.am
common.c
common.h
gui/GameConqueror.py
gui/backend.py
handlers.c

handlers: set: Introduce and use sm_check_process()
For setting values continuously in target memory it is annoying
having to interrupt the set handler manually once the target process
terminates. A function to detect if a process is running, a zombie,
or dead is required. The zombie and the error case should be treated
as dead so that we see the unlikely case that the kernel interface
changes.
The required check_process() function has been implemented for
ugtrain long time ago already and optimized recently. It checks if
/proc/$pid/status exists while opening it with fopen(). Then it reads
the first two lines with getline(), extracts the process state, and
returns an enum value for this. The method has proven working.
So take it over but without checking the process name. Set the target …

scanmem/GUI: Check if the target process is still running

---

handlers.c
maps.c
ptrace.c

Coverity Scan reports four locations with printf format issues.
%u should be %lu or %d should be %lu. This issue has existed since
2009 with the 64 bit support introduction.
So fix the reported issues.
Fixes #351

treewide: Fix printf format issues

---

.travis.yml

The Docker build was just a workaround for gcc-7. Now Travis-CI
provides an Ubuntu Bionic VM image. We do not need the further layer
of complexity any more. So drop the Docker build and build on Bionic.
Fixes #350

.travis.yml: Drop docker build and build on Bionic

---

maps.c

When calling alloca() for the file name in the getline() loop, then
this allocates more and more memory on the stack for all file names
within the same maps file. It has no clue about the scope/block for
which it should keep the memory. It keeps it for the whole
sm_readmaps() function. With too many memory regions, this crashes.
So replace this with a variable length array as this one respects
the scope/block it is running in, restores the stack pointer at the
start of each loop cycle and only keeps one file name on the stack
at once this way.
Fixes #368

maps: Replace alloca() with variable length array

---

gui/hexview.py

346de29..7cb8662
Those two commits fixed broken HexView dispaly in none Latin locale system.
Tested on Fedora 32 x86_64 LANG=[C, en_US, de_DE, en_UK, it_IT, zh_TW, zh_HK, ja_JP].
c9af3b7
Make sure test program also follow same AM_CFLAGS and take extra CFLAGS from ./configure CFLAGS=xxx
P.S: I got 4%~6% faster scan ./configure with CFLAGS=-O3 -g -march=native then CFLAGS=-O2 -g by compile with gcc 10 :smile:
Please be kind to review those changes.

fixed broken HexView dispaly in none Latin locale system

---

ptrace.c
scanroutines.c

glibc headers have 'uint' typedef'd to 'unsigned int', but this isn't guaranteed to be avaialble. Change to 'unsigned int' which is equivalent to fix building on musl.
Bug: https://bugs.gentoo.org/854840

Use 'unsigned int' instead of unofficial alias 'uint'

---

handlers.c

We stumbled upon a little issue in our own fork where we tried using `send_command`'s `get_output` parameter inside `scanmem.py` wrapper to retrieve the memory regions, but that only captures the stdout descriptor where lregions command outputs to stderr.
Another way to fix this would be to change `get_output` to also capture stderr but that would also grab other outputs that might not be necessary to programs using this as a library. This is why I opted to just change lregions' stderr to stdout so it's in line with other commands that have similar output, like list.
I'm not sure why we would want to output normal info to stderr instead of stdout for this case, unless the unbuffered aspect is desired particularly for this command.

Change lregions command to output to stdout instead of stderr
